# =============================================================================
# NON-AGENTIC MODE PROMPTS (Legacy - used with LLMClient direct API calls)
# These prompts receive piped-in code and metrics
# =============================================================================

# Step 1: Individual Program Summaries
META_STEP1_SYSTEM_MSG = (
    "You are an expert programming assistant analyzing an individual program. "
    "Create a standalone summary focusing on implementation details and "
    "evaluation feedback. Consider how this specific program performs and "
    "what implementation choices were made."
)

META_STEP1_USER_MSG = (
    "# Program to Analyze\n"
    "{individual_program_msg}\n\n"
    "# Instructions\n\n"
    "Create a standalone summary for this program using the following "
    "exact format:\n\n"
    "**Program Name: [Short summary name of the algorithm "
    "(up to 10 words)]**\n"
    "- **Implementation**: [Key implementation details (1-2 sentences)]\n"
    "- **Performance**: [Score/metrics summary (1 sentence)]\n"
    "- **Feedback**: [Key insights from evaluation (1-2 sentences)]\n\n"
    "Focus on:\n"
    "1. What specific implementation details were done\n"
    "2. How these details affected performance\n"
    "3. Implementation details that are relevant to the approach\n"
    "4. Any evaluation feedback that provides insights\n\n"
    "Keep the program summary concise but informative. "
    "Follow the format exactly."
)

# Step 2: Global Insights Scratchpad
META_STEP2_SYSTEM_MSG = (
    "You are an expert programming assistant analyzing specific program "
    "evaluation results to extract actionable optimization insights. Focus "
    "on concrete performance data and implementation details from the actual "
    "programs that were evaluated."
)

META_STEP2_USER_MSG = (
    "# Individual Program Summaries\n"
    "{individual_summaries}\n\n"
    "# Previous Global Insights (if any)\n"
    "{previous_insights}\n\n"
    "# Current Best Program\n"
    "{best_program_info}\n\n"
    "# Instructions\n\n"
    "Analyze the SPECIFIC program evaluation results above to extract "
    "concrete optimization insights. Look at the actual performance scores, "
    "implementation details, and evaluation feedback to identify patterns. "
    "Reference specific programs and their results.\n"
    "Make sure to incorporate the previous insights into the new insights.\n\n"
    "**CRITICAL: Pay special attention to the current best program and how it "
    "compares to other evaluated programs. Ensure the best program's successful "
    "patterns are prominently featured in your analysis.**\n\n"
    "Update or create insights in these sections:\n\n"
    "## Successful Algorithmic Patterns\n"
    "- Identify specific implementation changes that led to score "
    "improvements\n"
    "- Reference which programs achieved these improvements and their "
    "scores\n"
    "- **Highlight patterns from the current best program**\n"
    "- Note the specific techniques or approaches that worked "
    "(2-4 bullet points)\n\n"
    "## Ineffective Approaches\n"
    "- Identify specific implementation changes that worsened "
    "performance\n"
    "- Reference which programs had these issues and how scores were "
    "affected\n"
    "- Note why these approaches failed based on evaluation feedback "
    "(2-4 bullet points)\n\n"
    "## Implementation Insights\n"
    "- Extract specific coding patterns/techniques from the evaluated "
    "programs\n"
    "- **Analyze what makes the current best program effective**\n"
    "- Connect implementation details to their performance impact\n"
    "- Reference concrete examples from the program summaries "
    "(2-4 bullet points)\n\n"
    "## Performance Analysis\n"
    "- Analyze actual score changes and trends from the evaluated "
    "programs\n"
    "- **Compare other programs' performance against the current best**\n"
    "- Compare performance between different implementation "
    "approaches\n"
    "- Identify score patterns and correlations (2-4 bullet points)\n\n"
    "CRITICAL: Base insights on the ACTUAL individual program summaries, "
    "previous insights, and the current best program information. "
    "Reference specific program names, scores, and implementation details. "
    "Build upon previous insights with concrete evidence from the new evaluations. "
    "IMPORTANT: Make sure that the best results are not ignored and are "
    "prominently featured in your analysis."
    "Do not make recommendations for the next steps. ONLY PERFORM THE "
    "ANALYSIS."
)

# Step 3: Recommendations Generation
META_STEP3_SYSTEM_MSG = (
    "You are an expert programming assistant generating actionable "
    "recommendations for future program mutations based on successful "
    "patterns and insights."
)

META_STEP3_USER_MSG = (
    "# Global Insights\n"
    "{global_insights}\n\n"
    "# Previous Recommendations (if any)\n"
    "{previous_recommendations}\n\n"
    "# Current Best Program\n"
    "{best_program_info}\n\n"
    "# Instructions\n\n"
    "Based on the global insights above and the current best program, generate {max_recommendations} "
    "actionable recommendations for future program mutations. Each "
    "recommendation should be:\n\n"
    "1. **Specific**: Clear about what to implement or try\n"
    "2. **Actionable**: Something that can be directly applied\n"
    "3. **Evidence-based**: Grounded in the successful patterns identified\n"
    "4. **Diverse**: Cover different types of optimizations\n"
    "5. **Best-program informed**: Consider what makes the current best program successful\n\n"
    "Format as a numbered list:\n\n"
    "1. [Specific recommendation based on successful patterns]\n"
    "2. [Another recommendation focusing on different aspect]\n"
    "...\n\n"
    "**CRITICAL: Prioritize recommendations that build upon or extend the successful "
    "patterns from the current best program. Consider both incremental improvements "
    "to the best program's approach and novel variations that could surpass it.**\n\n"
    "Focus on the most promising approaches that have shown success in "
    "recent evaluations, especially those demonstrated by the best program. "
    "Avoid generic advice - provide 2-3 sentences per recommendation. "
    "DO NOT RECOMMEND CHANGING THE EVALUATION CODE. ONLY "
    "MAKE ALGORITHMIC RECOMMENDATIONS."
)


# =============================================================================
# AGENTIC MODE PROMPTS (New - agent explores results directory itself)
# Agent reads files directly and writes output to _meta/ directory
# =============================================================================

AGENTIC_META_SYSTEM_MSG = (
    "You are an expert programming assistant analyzing evolution results. "
    "You have full access to the results directory and can read all files. "
    "Write your analysis output to the _meta/ directory."
)

# Step 1: Analyze individual programs (agent reads code and metrics from disk)
AGENTIC_META_STEP1_USER_MSG = (
    "# Task: Analyze Programs from Generations {start_gen} to {end_gen}\n\n"
    "## Where to Find Data\n"
    "For each generation N, you can read:\n"
    "- **Workspace Code**: all source files under `gen_N/` (the whole generation workspace)\n"
    "- **Metrics**: `gen_N/results/metrics.json` - contains `combined_score`, `correct`, `details`, and `public` metrics\n\n"
    "## Your Task\n"
    "1. Read the workspace code and metrics for each generation from {start_gen} to {end_gen}\n"
    "2. Create the output directory if needed: `_meta/summaries/`\n"
    "3. For each program, write a summary file to: `_meta/summaries/gen_N.md`\n\n"
    "## Summary Format\n"
    "Each summary file should contain:\n"
    "```\n"
    "# Generation N Summary\n\n"
    "- **Score**: [combined_score from metrics.json]\n"
    "- **Correct**: [Yes/No from metrics.json]\n"
    "- **Implementation**: [Key implementation details you discovered in the code]\n"
    "- **Performance**: [Notable metrics from public metrics]\n"
    "- **Insights**: [What makes this approach work or fail, based on code analysis]\n"
    "```\n\n"
    "## Important\n"
    "- Read the actual code files to understand the implementation\n"
    "- Compare approaches across generations to identify patterns\n"
    "- Be specific about what algorithmic choices were made\n"
    "- Note any helper files or multi-file structures"
)

# Step 2: Generate global insights (agent reads summaries and best program)
AGENTIC_META_STEP2_USER_MSG = (
    "# Task: Generate Global Insights\n\n"
    "## Context\n"
    "You have already created individual summaries in `_meta/summaries/`.\n"
    "The current best program is **generation {best_gen}** with score **{best_score}**.\n\n"
    "## Where to Find Data\n"
    "- Individual summaries: `_meta/summaries/gen_*.md`\n"
    "- Best program code: everything under `gen_{best_gen}/` (whole workspace)\n"
    "- Best program metrics: `gen_{best_gen}/results/metrics.json`\n"
    "- Previous insights (if any): `_meta/insights.md`\n\n"
    "## Your Task\n"
    "1. Read all individual summaries from `_meta/summaries/`\n"
    "2. Read the best program's code to understand why it succeeds\n"
    "3. If `_meta/insights.md` exists, incorporate previous insights\n"
    "4. Write updated global insights to: `_meta/insights.md`\n\n"
    "## Insights Format\n"
    "Structure your insights file with these sections:\n"
    "```\n"
    "# Global Insights\n\n"
    "## Successful Patterns\n"
    "[What approaches led to score improvements - reference specific generations]\n\n"
    "## Ineffective Approaches\n"
    "[What approaches worsened performance - explain why they failed]\n\n"
    "## Implementation Insights\n"
    "[Key coding patterns/techniques - what makes the best program effective]\n\n"
    "## Performance Analysis\n"
    "[Score trends, correlations between approaches and results]\n"
    "```\n\n"
    "## Important\n"
    "- Reference specific generation numbers and their scores\n"
    "- Highlight what makes generation {best_gen} the current best\n"
    "- Be concrete about implementation details, not generic advice\n"
    "- Build upon any previous insights rather than replacing them"
)

# Step 3: Generate recommendations (agent reads insights and writes recommendations)
AGENTIC_META_STEP3_USER_MSG = (
    "# Task: Generate Recommendations\n\n"
    "## Context\n"
    "The current best program is **generation {best_gen}** with score **{best_score}**.\n\n"
    "## Where to Find Data\n"
    "- Global insights: `_meta/insights.md`\n"
    "- Best program code: everything under `gen_{best_gen}/` (whole workspace)\n"
    "- Previous recommendations (if any): `_meta/recommendations.md`\n\n"
    "## Your Task\n"
    "1. Read the global insights from `_meta/insights.md`\n"
    "2. Read the best program's code to understand current state\n"
    "3. Generate {max_recommendations} actionable recommendations\n"
    "4. Write to: `_meta/recommendations.md`\n\n"
    "## Recommendations Format\n"
    "```\n"
    "# Recommendations\n\n"
    "1. **[Specific recommendation title]**\n"
    "   [2-3 sentences explaining what to implement and why, grounded in insights]\n\n"
    "2. **[Another recommendation]**\n"
    "   [Explanation...]\n\n"
    "...\n"
    "```\n\n"
    "## Requirements\n"
    "Each recommendation must be:\n"
    "- **Specific**: Clear about what code changes to make\n"
    "- **Actionable**: Can be directly implemented\n"
    "- **Evidence-based**: Grounded in the successful patterns from insights\n"
    "- **Diverse**: Cover different optimization approaches\n\n"
    "## Important\n"
    "- Prioritize improvements to the best program's approach\n"
    "- Consider both incremental improvements and novel variations\n"
    "- DO NOT recommend changes to evaluation code\n"
    "- Focus on algorithmic and implementation improvements only"
)
